{
 "title": "PROVA1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Volume ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"VOLUME\" \nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "V(t)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"VOLUME\" \nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "content": "# **MARIO ROSSI**\n\n - COVID Patient \n - Obese \n - ARDS \n - No weaning",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"PRESSURE\"\nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 5 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Pressure CmH2O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"PRESSURE\"\nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PPeak",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"PRESSURE\"\nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PEEP value",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"PRESSURE\"\nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"PRESSURE\" * 50\nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "MODE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"PRESSURE\"\nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "FLOW L/min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"FLOW\"\nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "exp/min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"PRESSURE\" / 2.4\nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "O2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"FLOW\" * 5\nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Static Compliance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  \"VOLUME\"*10\nFROM paziente0\nWHERE\n  $__unixEpochFilter(time)\nORDER BY 1"
    }
   ]
  }
 ]
}